"""beds

Revision ID: 1a120ac19c2c
Revises: 7ae6a7c47028
Create Date: 2026-08-21 14:54:05.876191
"""
from alembic import op
import sqlalchemy as sa


revision = '1a120ac19c2c'
down_revision = '7ae6a7c47028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accommodation_assignments', sa.Column('bed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accommodation_assignments', 'beds', ['bed_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accommodation_assignments', type_='foreignkey')
    op.drop_column('accommodation_assignments', 'bed_id')
    op.drop_table('beds')
    # ### end Alembic commands ###
