"""attachments and comments

Revision ID: 7ae6a7c47028
Revises: fe436b0491f6
Create Date: 2026-08-21 14:14:13.143898
"""
from alembic import op
import sqlalchemy as sa


revision = '7ae6a7c47028'
down_revision = 'fe436b0491f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_item_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=160), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('storage_path', sa.String(length=600), nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.String(length=120), nullable=True))
    op.add_column('documents', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('is_upload', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_upload')
    op.drop_column('documents', 'size_bytes')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'storage_path')
    op.drop_table('comments')
    # ### end Alembic commands ###
